# Generated by Django 5.2.5 on 2025-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Book_id', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('Genre', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
